steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "us-central1-docker.pkg.dev/gcp-class-17/frontend/frontend-image",
      "."
    ]

  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "us-central1-docker.pkg.dev/gcp-class-17/frontend/frontend-image"
    ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        BACKEND_URL=$(gcloud run services describe bank-backend \
          --region us-central1 \
          --format='value(status.url)')

        echo "Deploying frontend with API_BASE_URL=$BACKEND_URL"

        gcloud run deploy bank-frontend \
          --image us-central1-docker.pkg.dev/gcp-class-17/frontend/frontend-image \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars "API_BASE_URL=$BACKEND_URL"
