options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BACKEND_URL: "https://bank-backend-4uybablfqq-uc.a.run.app"

steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      "build",
      "-t", "us-central1-docker.pkg.dev/gcp-class-17/bank-frontend/frontend-image:${SHORT_SHA}",
      "."
    ]

  - name: gcr.io/cloud-builders/docker
    args: [
      "push",
      "us-central1-docker.pkg.dev/gcp-class-17/bank-frontend/frontend-image:${SHORT_SHA}"
    ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        BACKEND_URL="$(gcloud run services describe bank-backend \
          --region us-central1 \
          --format='value(status.url)')"

        # Deploy and inject backend URL as an env var for the frontend container
        gcloud run deploy bank-frontend \
          --image us-central1-docker.pkg.dev/gcp-class-17/bank-frontend/frontend-image:${SHORT_SHA} \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars "API_BASE_URL=${_BACKEND_URL}"

#change 