
substitutions:
  _REGION: us-central1        
  _LOCATION: us-central1         
  _AR_REPO: bank-frontend   
  _IMAGE: frontend              
  _SERVICE: bank-frontend        
  _TAG: '${SHORT_SHA}'
  _BACKEND_SERVICE: bank-backend 

steps:
  - id: build-image
    name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t','${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${_TAG}',
        '.'
      ]

  - id: push-image
    name: gcr.io/cloud-builders/docker
    args:
      [
        'push',
        '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${_TAG}'
      ]

  - id: deploy-to-cloud-run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        BACKEND_URL=$(gcloud run services describe "${_BACKEND_SERVICE}" \
          --region "${_REGION}" \
          --format='value(status.url)')

        echo "Deploying ${_SERVICE} with API_BASE_URL=${BACKEND_URL}"

        gcloud run deploy "${_SERVICE}" \
          --image "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${_TAG}" \
          --region "${_REGION}" \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "API_BASE_URL=${BACKEND_URL}"

# small change again